name: release

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  release:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          ref: main
          fetch-depth: 0
      - run: npm i -g --force corepack && corepack enable
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build (stub)
        run: pnpm build:stub
      - name: Release
        run: ./scripts/release.sh
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
          NPM_CONFIG_PROVENANCE: true
